version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.0.2-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.0.2-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:3.0.2-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-zeppelin:
    build: .
    image: spark-zeppelin
    container_name: spark-zeppelin
    depends_on:
      - spark-master
    ports:
      - "0.0.0.0:8888:8080"
    volumes:
      - ./pyspark-samples:/workspace/pyspark-samples
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/spark"

  database:
    image: mysql:8
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE = hong_study
      - MYSQL_ROOT_PASSWORD = 
      - tz=Asia/Seoul
    
    

  